// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrchestratorAPI.Data;

#nullable disable

namespace OrchestratorAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720051722_AddPipelineStageStatuses")]
    partial class AddPipelineStageStatuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("OrchestratorAPI.Models.PipelineFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("PipelineFiles");
                });

            modelBuilder.Entity("OrchestratorAPI.Models.PipelineRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BackendChanged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeployStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DocsOnly")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GitHubRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GitHubRunNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubRunUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubWorkflowName")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfFiles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TestsChanged")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PipelineRuns");
                });

            modelBuilder.Entity("OrchestratorAPI.Models.PipelineFile", b =>
                {
                    b.HasOne("OrchestratorAPI.Models.PipelineRun", "Run")
                        .WithMany("Files")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("OrchestratorAPI.Models.PipelineRun", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
